### ISSUE TITLE
Splitting hardware and software to layers

### ISSUE THREAD

**Issue by huseyinkozan** [OATS-Group/meta-isoblue#1]
Hello,

Is it possible to split layer into hardware and software layers ? I want to use same hardware but different software stack.

I forked and trying to remove kafka, librdkafka and related codes. Can you guide me, if you dont have any plans for splitting ?

**Comment by wang701** [comment]
Hello huseyinkozan,

I feel like you misunderstood the content of the repo. The content of this repo is all software recipes for ISOBlue2. There is no hardware description recipe.

If you do not want to include a recipe, you can disable it by removing the corresponding the top level `bblayers.conf` or layer-specific `layer.conf` in your build directory.

That being said, I think what you are also looking for is the layers that describe the Toradex hardware, which, unfortunately, still a work in progress for us to put them together with ISOBlue recipes. What we want to do eventually is to integrate `meta-isoblue` and `meta-isoblue-demos` into the Toradex build structure and create one single repo that will build everything. Both repos resides in the build structure (specifically under `oe-core/layers/`) that Toradex provides. 

You can set up the Toradex bitbake build structure by following [these instructions](http://developer.toradex.com/knowledge-base/board-support-package/openembedded-(core)). The repo I used can be found [here](http://git.toradex.com/cgit/toradex-bsp-platform.git/).

**Comment by huseyinkozan** [comment]
@wang701, Thank you for the clarification. I will try to learn layering. Closing this issue.
